### PR TITLE
Generated  models and request builders

### PR DESCRIPTION
**Pull request by andrueastman**
This pull request was automatically created by Azure Pipelines. **Important** Check for unexpected deletions or changes in this PR.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1856)

### CODE REVIEW

**Comment by andrueastman** [comment]
@baywet A number of `*CollectionResponse` model files have been dropped from the models in the generation. 
Any chance this is expected? Or were these erroneously generated by Kiota to warrant a fix?

**Comment by baywet** [comment]
@andrueastman thanks for checking. Yes this is expected. It seems the conversion lib is a bit too verbose when projecting the collection responses and a number of them are not used anywhere.
Although this could arguably be considered a breaking change, I think we can rule it as a bug because it's highly unlikely that anyone is using any of those types, and if they are the patch is simple, use the parent type collection response.

**Comment by andrueastman** [comment]
Thanks for confirming @baywet 

> Although this could arguably be considered a breaking change, I think we can rule it as a bug because it's highly unlikely that anyone is using any of those types, and if they are the patch is simple, use the parent type collection response

I agree. The collection models are indeed not really used and seem to be derived instances which aren't really used, and the parent types should do a downcast on deserialization. I'll do a check to confirm nothing unexpected passes through before the merge.

**Comment by baywet** [comment]
@andrueastman this is what I was using to compare what was deleted during my tests

```PowerShell
$value = git diff master --diff-filter=D | ? {$_.Contains("--- a")}
$value = $value -replace ".cs", ""
$value = $value -replace "--- a/src/Microsoft.Graph/Generated/Models/", ""
$value | ?{$_.Contains("CollectionResponse") -eq $false} | measure
```

**Comment by andrueastman** [comment]
This mostly looks good except for the models used in callbacks and related entities.

This is mainly rooted from the `changeNotificationCollectionResponse` and `CommsNotificationCollectionResponse` which may break users using the models to deserialize callbacks. 

https://learn.microsoft.com/en-us/graph/webhooks-with-resource-data

At the moment, to properly support this, the conversion library may need to somehow add the `callbacks` to the `/subscriptions` path and then Kiota would need to be able use the `callbacks` section to generate the model. 

Example openAPI at https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/callback-example.yaml#L34

In the interim we may need to move these 7 selected models in a separate folder to avoid being overwritten in subsequent generations to avoid breaking users and if/when the support for callbacks is done, they would be removed/replaced without side effects. 

Thoughts @baywet?

**Comment by baywet** [comment]
Thanks, I'm fine with either moving to a separate folder with same namespace to avoid breaking people or moving to core. Keeping it in the service lib is probably better as it allows us to have different versions between v1 and beta.

**Pull request merged**
