### PR TITLE
Added configuration so that we generate intellisense

### PR DESCRIPTION
**Pull request by MIchaelMainer**
This will be added to nuget package with dotnet pack. There are some bad comments that will need to be cleaned up in our templates. Next step will be to add comments from the docs.

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
This takes about 15 minute to generate the IntelliSense file from the source. 7mb intellisense.

**Comment by MIchaelMainer** [comment]
Addresses issue #144

**Comment by cbales** [comment]
Have you seen any performance hits when using this in a sample? It looks like there were some issues with Intellisense loading slowly for large projects in previous versions of VS.

**Comment by MIchaelMainer** [comment]
You bring up a great point. This generates a 7MB intellisense file. VS is already challenged when I delete and add files after generation. Test discovery seems to take a while too. I'm going to confirm the experience before merging this in.

**Comment by MIchaelMainer** [comment]
The Intellisense file performance in VS is fine. We are good to merge

**Pull request merged**
