### PR TITLE
Avoid extra memory allocation when doing chunked upload for large file

### PR DESCRIPTION
**Pull request by zsybupt**
### Changes proposed in this pull request
-  Avoid extra memory allocation when doing chunked upload
ChunkedUploadProvider trys to help with large file uploading, it divides the large stream to chunk-size stream and upload each one by one. The current implementation allocate maxChunksize of byte[] buffer each time:
```c#
  var readBuffer = new byte[this.maxChunkSize]; // extra allocation
```
and an extra stream copy:

```c#
    //extra copy 
    await this.uploadStream.ReadAsync(readBuffer, 0, request.RangeLength).ConfigureAwait(false);

       while (true)
       {
             using (var requestBodyStream = new MemoryStream(request.RangeLength))
             {
                 await requestBodyStream.WriteAsync(readBuffer, 0, request.RangeLength).ConfigureAwait(false);
                 requestBodyStream.Seek(0, SeekOrigin.Begin);
                 ...
             }
       }
```
If there is a total 500MiB size file, open a FileStream with a 10MiB max chunk size, it will allocate a 10 * 1024 * 1024 size buffer 50 times (extra 500MiB memory allocation), and do 100 times buffer operations (50 read and 50 write).

Because the upload stream supports seek and read operation, this pull request provide a ReadOnlySubStream to represent a chunk of a upload stream to save memory when dealing with large file and remove the extra copy operations

### CODE REVIEW

**Comment by zsybupt** [comment]
@MIchaelMainer  @darrelmiller anyone can help review this?

**Comment by zsybupt** [comment]
@darrelmiller  Thanks for your quick reply.

1. I am sorry that it is not the buffer, it is the memorystream, please check this line:[MemoryStream Allocated](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/4186d848cabfd93263c1d9a42ae3473dd0560282/src/Microsoft.Graph/Requests/Helpers/ChunkedUploadProvider.cs#L172), a new MemoryStream is allocated for each chunk request.
2. This SubStream class is port from System.IO.Compression, they have a very similar scenario of dealing with ZipAchrive:[System.IO.Compression](https://github.com/dotnet/corefx/blob/d59f6e5a1bdabdd05317fd727efb59345e328b80/src/System.IO.Compression/src/System/IO/Compression/ZipCustomStreams.cs#L147), and I have use this in my production now. 

For a 170MiB file
## Before
defaultmemorystream
## After
readonlysubstream

**Comment by zsybupt** [comment]
Sorry that my PC language is Chinese, the original ChunkedUploadProvider consume about 113.4 MiB memory, with the ReadOnlySubStream the memory reduce to 13.9 MiB

**Comment by zsybupt** [comment]
Any updates of this pr ？

**Comment by andrueastman** [comment]
@zsybupt 
Thanks a lot for making this PR. It does indeed improve things by avoiding extra memory allocation on upload.

If it is okay, I will be merging this PR into the branch **task/uploadTask** so as to enable us to do more tests and build upon this work to improve the UploadProvider so as to provide more usability such as giving progress callbacks during upload.

**Comment by zsybupt** [comment]
@andrueastman ok,Thanks

**Pull request merged**
